version: '3'

tasks:
  default:
    cmds:
      - task: lint
      - task: build
      - task: build:local

  lint:
    cmds:
      - golangci-lint run -v --fix

  install:
    cmds:
      - >
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
        sh -s -- -b $(go env GOPATH)/bin latest

  build:local:
    cmds:
      - go build -o spotifip-local .

  build:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o spotifip .

  clean:
    cmds:
      - go clean
