version: '3'

tasks:
  default:
    cmds:
      - task: lint
      - task: build:local
      - task: build:linux:amd64

  lint:
    cmds:
      - golangci-lint run -v --fix

  build:local:
    cmds:
      - go build -o spotifip-local .

  build:linux:amd64:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o spotifip .

  clean:
    cmds:
      - go clean
