name: deploy-backend
on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: deploy-backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: SCP command to transfer files via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "backend/spotifip"
        target: "/home/spotifip"
        strip_components: 1
